name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: "Node.js ${{ matrix.node-version }} | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Webpack Build
      run: |
        npm ci
        npm run webpack
